
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Cricped@123
    url: jdbc:mysql://cric_pred_mysql:3306/prediction_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

dataJson:
  url: https://raw.githubusercontent.com/aniket7777777/cricpred/master/Data_Matches.json
